// CHARGEOPS — EV Fleet & Charging Operations Console
// Enterprise Fleet Dataset (Voltis Integration)

const FLEET_DATA = {
  kpis: {
    totalVehicles: 28,
    activeOnRoad: 14,
    chargingNow: 7,
    availableIdle: 5,
    inMaintenance: 2,
    fleetAverageSoc: 73.8,
    depotGridPowerKw: 1420,
    depotMaxCapKw: 2000,
    energyRateKwh: "$0.128 / kWh (Off-Peak)",
    fleetEfficiency: "21.4 kWh / 100 km"
  },

  vehicles: [
    {
      id: "EV-409",
      vin: "1VTCG500L993821",
      model: "Voltis Cargo 500 Long-Range",
      plate: "79A-884.21",
      driver: "Elena Rostova",
      status: "Available", // Available, Charging, En Route, Maintenance
      soc: 76,
      targetSoc: 90,
      batteryKwh: 110,
      currentRangeKm: 218,
      ratedRangeKm: 340,
      soh: 98.4, // State of Health %
      batteryTemp: 23.8,
      cellDeltaMv: 12,
      tirePressurePsi: 41.5,
      location: "Depot Central — Bay A4",
      assignedRoute: null,
      chargerId: null,
      chargeKw: 0,
      etaFull: null,
      nextDeparture: "11:30 (Scheduled)",
      efficiencyKwh100km: 22.1,
      odometerKm: 38420,
      lastInspection: "2026-08-28"
    },
    {
      id: "EV-104",
      vin: "1VTCG350S449102",
      model: "Voltis Cargo 350 Standard",
      plate: "51D-921.84",
      driver: "Marcus Vance",
      status: "Charging",
      soc: 28,
      targetSoc: 85,
      batteryKwh: 78,
      currentRangeKm: 82,
      ratedRangeKm: 240,
      soh: 96.2,
      batteryTemp: 29.4,
      cellDeltaMv: 18,
      tirePressurePsi: 40.2,
      location: "Depot Central — Bay DC-02",
      assignedRoute: null,
      chargerId: "DC-02",
      chargeKw: 124.5,
      etaFull: "42 min to 85%",
      nextDeparture: "13:15",
      efficiencyKwh100km: 21.0,
      odometerKm: 64180,
      lastInspection: "2026-09-02"
    },
    {
      id: "EV-202",
      vin: "1VTCG500L771239",
      model: "Voltis Cargo 500 Long-Range",
      plate: "51D-339.12",
      driver: "Takahashi Ken",
      status: "En Route",
      soc: 64,
      targetSoc: 100,
      batteryKwh: 110,
      currentRangeKm: 186,
      ratedRangeKm: 340,
      soh: 97.9,
      batteryTemp: 25.1,
      cellDeltaMv: 14,
      tirePressurePsi: 41.0,
      location: "Highway 1A — Sector 4",
      assignedRoute: "RT-108 (Metro Hub Deliveries)",
      chargerId: null,
      chargeKw: 0,
      etaFull: null,
      nextDeparture: "In Transit (ETA 12:40)",
      efficiencyKwh100km: 23.4,
      odometerKm: 42100,
      lastInspection: "2026-08-15"
    },
    {
      id: "EV-315",
      vin: "1VTCG500L112849",
      model: "Voltis Cargo 500 Long-Range",
      plate: "79A-402.19",
      driver: "Sarah Jenkins",
      status: "Charging",
      soc: 82,
      targetSoc: 90,
      batteryKwh: 110,
      currentRangeKm: 248,
      ratedRangeKm: 340,
      soh: 99.1,
      batteryTemp: 26.2,
      cellDeltaMv: 11,
      tirePressurePsi: 42.0,
      location: "Depot Central — Bay DC-01",
      chargerId: "DC-01",
      chargeKw: 48.2, // Tapering near 85%
      etaFull: "14 min to 90%",
      nextDeparture: "10:45",
      efficiencyKwh100km: 21.8,
      odometerKm: 21900,
      lastInspection: "2026-09-05"
    },
    {
      id: "EV-108",
      vin: "1VTCG350S990214",
      model: "Voltis Cargo 350 Standard",
      plate: "51D-582.01",
      driver: "David Nguyen",
      status: "Available",
      soc: 89,
      targetSoc: 100,
      batteryKwh: 78,
      currentRangeKm: 214,
      ratedRangeKm: 240,
      soh: 97.5,
      batteryTemp: 22.0,
      cellDeltaMv: 10,
      tirePressurePsi: 41.2,
      location: "Depot Central — Staging Bay B2",
      assignedRoute: null,
      chargerId: null,
      chargeKw: 0,
      etaFull: null,
      nextDeparture: "14:00",
      efficiencyKwh100km: 20.8,
      odometerKm: 51200,
      lastInspection: "2026-08-10"
    },
    {
      id: "EV-512",
      vin: "1VTEH800X381902",
      model: "Voltis HeavyHaul 800 (Class 8)",
      plate: "79C-119.82",
      driver: "Robert Kowalski",
      status: "Charging",
      soc: 45,
      targetSoc: 85,
      batteryKwh: 450,
      currentRangeKm: 180,
      ratedRangeKm: 420,
      soh: 98.8,
      batteryTemp: 31.5,
      cellDeltaMv: 21,
      tirePressurePsi: 105.0,
      location: "Depot Central — Bay MCS-01",
      chargerId: "MCS-01",
      chargeKw: 340.0, // Megawatt Charging System
      etaFull: "48 min to 85%",
      nextDeparture: "14:30",
      efficiencyKwh100km: 88.5,
      odometerKm: 19400,
      lastInspection: "2026-09-08"
    },
    {
      id: "EV-209",
      vin: "1VTCG500L882190",
      model: "Voltis Cargo 500 Long-Range",
      plate: "51D-772.33",
      driver: "Liam Thorne",
      status: "En Route",
      soc: 42,
      targetSoc: 100,
      batteryKwh: 110,
      currentRangeKm: 122,
      ratedRangeKm: 340,
      soh: 95.8,
      batteryTemp: 28.3,
      cellDeltaMv: 16,
      tirePressurePsi: 40.8,
      location: "North Port Ring Expressway",
      assignedRoute: "RT-114 (Maritime Freight Link)",
      chargerId: null,
      chargeKw: 0,
      etaFull: null,
      nextDeparture: "In Transit (ETA 13:10)",
      efficiencyKwh100km: 24.2,
      odometerKm: 78900,
      lastInspection: "2026-07-22"
    },
    {
      id: "EV-112",
      vin: "1VTCG350S228190",
      model: "Voltis Cargo 350 Standard",
      plate: "51D-664.18",
      driver: "Ana Morales",
      status: "Maintenance",
      soc: 18,
      targetSoc: 80,
      batteryKwh: 78,
      currentRangeKm: 46,
      ratedRangeKm: 240,
      soh: 92.1,
      batteryTemp: 34.2,
      cellDeltaMv: 42, // Thermal and cell imbalance
      tirePressurePsi: 38.5,
      location: "Service Bay M-02",
      assignedRoute: null,
      chargerId: null,
      chargeKw: 0,
      etaFull: null,
      nextDeparture: "Grounding — Thermal Investigation",
      efficiencyKwh100km: 22.9,
      odometerKm: 94200,
      lastInspection: "2026-09-15"
    },
    {
      id: "EV-330",
      vin: "1VTCG500L451299",
      model: "Voltis Cargo 500 Long-Range",
      plate: "79A-901.44",
      driver: "Hassan Ali",
      status: "Charging",
      soc: 68,
      targetSoc: 85,
      batteryKwh: 110,
      currentRangeKm: 198,
      ratedRangeKm: 340,
      soh: 98.0,
      batteryTemp: 27.1,
      cellDeltaMv: 13,
      tirePressurePsi: 41.8,
      location: "Depot Central — Bay DC-04",
      chargerId: "DC-04",
      chargeKw: 112.0,
      etaFull: "22 min to 85%",
      nextDeparture: "11:50",
      efficiencyKwh100km: 22.0,
      odometerKm: 33100,
      lastInspection: "2026-08-30"
    },
    {
      id: "EV-415",
      vin: "1VTCG500L773321",
      model: "Voltis Cargo 500 Long-Range",
      plate: "79A-312.90",
      driver: "Chen Wei",
      status: "Available",
      soc: 94,
      targetSoc: 100,
      batteryKwh: 110,
      currentRangeKm: 298,
      ratedRangeKm: 340,
      soh: 99.4,
      batteryTemp: 21.9,
      cellDeltaMv: 9,
      tirePressurePsi: 42.1,
      location: "Depot Central — Staging Bay B1",
      assignedRoute: null,
      chargerId: null,
      chargeKw: 0,
      etaFull: null,
      nextDeparture: "15:00",
      efficiencyKwh100km: 21.5,
      odometerKm: 14200,
      lastInspection: "2026-09-10"
    }
  ],

  // 142 km Dispatch Scenario Data
  heroDispatchOrder: {
    id: "DSP-8842",
    title: "Express Cold-Chain Logistics Hub Delivery",
    origin: "Central Depot (Terminal 4)",
    destination: "North Logistics Industrial Park (Warehouse 9)",
    distanceKm: 142,
    cargoWeightKg: 1850,
    elevationGainM: 320,
    ambientTempC: 14,
    requiredEnergyEstKwh: 48.6,
    requiredMinimumSoc: 65, // %
    recommendedMinimumSoc: 72, // with +25km buffer
    timeSensitiveArrival: "13:30 (Max deadline)",
    candidates: [
      {
        vehicleId: "EV-104",
        soc: 28,
        estRangeKm: 82,
        deficitKm: -60,
        eligible: false,
        rejectionReason: "Range Deficit: Needs 142 km + 25 km safety reserve (167 km). Only 82 km available at 28% SOC.",
        actionNeeded: "Hold on Fast Charge DC-02 until 12:45"
      },
      {
        vehicleId: "EV-409",
        soc: 76,
        estRangeKm: 218,
        deficitKm: +76,
        eligible: true,
        matchScore: 98,
        approvalReason: "Optimal Energy Match: 218 km range easily clears 142 km route + 76 km reserve buffer. Battery conditioned at 23.8°C.",
        actionNeeded: "Ready for immediate departure"
      },
      {
        vehicleId: "EV-108",
        soc: 89,
        estRangeKm: 214,
        deficitKm: +72,
        eligible: true,
        matchScore: 91,
        approvalReason: "Viable Secondary: Standard range cargo van, but reserved for 14:00 inter-city shuttle.",
        actionNeeded: "Secondary backup"
      }
    ]
  },

  // Chargers
  chargers: [
    { id: "DC-01", type: "DC Fast 150kW", status: "Active", currentKw: 48.2, vehicleId: "EV-315", efficiency: "94.8%", temp: "38°C" },
    { id: "DC-02", type: "DC Fast 150kW", status: "Active", currentKw: 124.5, vehicleId: "EV-104", efficiency: "93.9%", temp: "44°C" },
    { id: "DC-03", type: "DC Fast 150kW", status: "Available", currentKw: 0, vehicleId: null, efficiency: "99.0%", temp: "24°C" },
    { id: "DC-04", type: "DC Fast 150kW", status: "Active", currentKw: 112.0, vehicleId: "EV-330", efficiency: "94.1%", temp: "41°C" },
    { id: "DC-05", type: "DC Fast 150kW", status: "Throttled", currentKw: 42.0, vehicleId: "EV-218", efficiency: "91.2%", temp: "58°C" },
    { id: "MCS-01", type: "Megawatt 500kW", status: "Active", currentKw: 340.0, vehicleId: "EV-512", efficiency: "95.6%", temp: "46°C" },
    { id: "AC-01", type: "AC Level-2 22kW", status: "Active", currentKw: 21.8, vehicleId: "EV-105", efficiency: "98.2%", temp: "22°C" },
    { id: "AC-02", type: "AC Level-2 22kW", status: "Available", currentKw: 0, vehicleId: null, efficiency: "99.2%", temp: "21°C" }
  ],

  // Priority Queue for Charging Stalls
  chargingQueue: [
    { rank: 1, vehicleId: "EV-104", currentSoc: 28, targetSoc: 85, bayAssigned: "DC-02", powerAllocatedKw: 125, priority: "URGENT_DEPARTURE", deadline: "13:15" },
    { rank: 2, vehicleId: "EV-209", currentSoc: 42, targetSoc: 80, bayAssigned: "Queued for DC-01", powerAllocatedKw: 0, priority: "STANDARD", deadline: "14:30" },
    { rank: 3, vehicleId: "EV-112", currentSoc: 18, targetSoc: 70, bayAssigned: "Held (Inspection)", powerAllocatedKw: 0, priority: "MAINTENANCE_HOLD", deadline: "Indefinite" }
  ],

  // Live Alerts
  alerts: [
    { id: "ALT-901", level: "warning", time: "10:14:22", title: "Charger DC-05 Thermal Derating", desc: "Cabinet internal temperature reached 58°C. Charging rate throttled from 150kW to 42kW to protect power electronics." },
    { id: "ALT-902", level: "critical", time: "09:48:10", title: "Cell Voltage Delta Anomaly on EV-112", desc: "Cell #42 delta exceeds 40mV threshold (42mV measured). Recommended grounding for battery pack balancing." },
    { id: "ALT-903", level: "info", time: "09:00:00", title: "Smart Peak-Shaving Engaged", desc: "Depot power ceiling capped at 2,000 kW during grid high-tariff window (09:00 - 11:30). Saved est. $420." }
  ]
};

// Export to window for access
if (typeof window !== "undefined") {
  window.FLEET_DATA = FLEET_DATA;
}
